LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)


FRAMEWORK_GRAPHICS_PATH		:= frameworks/base/core/jni/android/graphics
EXTERNAL_SKIA_PATH			:= external/skia
SYSTEM_CORE_PATH			:= system/core

LOCAL_MODULE		:= SupportPdf
LOCAL_C_INCLUDES	:= \
				jni/$(FRAMEWORK_GRAPHICS_PATH) \
				jni/$(EXTERNAL_SKIA_PATH)/core \
				jni/$(SYSTEM_CORE_PATH)
						
LOCAL_SRC_FILES		:= \
				SupportPdf.cpp \
				$(FRAMEWORK_GRAPHICS_PATH)/pdf/PdfDocument.cpp \
				$(FRAMEWORK_GRAPHICS_PATH)/pdf/PdfEditor.cpp \
				$(FRAMEWORK_GRAPHICS_PATH)/pdf/PdfRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkAAClip.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkAnnotation.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkAdvancedTypefaceMetrics.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkAlphaRuns.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBBHFactory.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBBoxRecord.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBBoxHierarchyRecord.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmap.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapDevice.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapHeap.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapProcShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapProcState.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapProcState_matrixProcs.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmapScaler.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBitmap_scroll.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitMask_D32.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitRow_D16.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitRow_D32.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitter_A8.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitter_ARGB32.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitter_RGB16.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBlitter_Sprite.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkChunkAlloc.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkClipStack.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkColor.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkColorFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkColorTable.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkComposeShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkConfig8888.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkConvolver.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkCubicClipper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkData.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDataTable.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDebug.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDeque.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDevice.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDeviceLooper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDeviceProfile.cpp \
				$(EXTERNAL_SKIA_PATH)/lazy/SkDiscardableMemoryPool.cpp \
				$(EXTERNAL_SKIA_PATH)/lazy/SkDiscardablePixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDistanceFieldGen.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDither.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDraw.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkDrawLooper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkEdgeBuilder.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkEdgeClipper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkEdge.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkError.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFilterProc.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFilterShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFlattenable.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFlattenableSerialization.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFloat.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFloatBits.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFont.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFontHost.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFontDescriptor.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFontStream.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkGeometry.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkGlyphCache.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkGraphics.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkInstCnt.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkImageInfo.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkImageGenerator.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkLocalMatrixShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkLineClipper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMallocPixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMask.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMaskFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMaskGamma.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMath.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMatrix.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMatrixClipStateMgr.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMetaData.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkMipMap.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPackBits.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPaint.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPaintOptionsAndroid.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPaintPriv.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPath.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPathHeap.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPathMeasure.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPathRef.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPicture.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPictureFlat.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPicturePlayback.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPictureRecord.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPictureRecorder.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPictureShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPictureStateTree.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPoint.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkProcSpriteBlitter.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkPtrRecorder.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkQuadClipper.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkQuadTree.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRasterClip.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRasterizer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkReadBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRecordDraw.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRecordOpts.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRecorder.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRecording.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRect.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRefDict.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRegion.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRegion_path.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRRect.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkRTree.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScaledImageCache.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScalar.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScalerContext.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScan.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScan_AntiPath.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScan_Antihair.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScan_Hairline.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkScan_Path.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkShader.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkSpriteBlitter_ARGB32.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkSpriteBlitter_RGB16.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkStream.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkString.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkStringUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkStroke.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkStrokeRec.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkStrokerPriv.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkTileGrid.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkTLS.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkTSearch.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkTypeface.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkTypefaceCache.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkUnPreMultiply.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkValidatingReadBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkVertState.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkWriteBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkWriter32.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkXfermode.cpp \
				$(EXTERNAL_SKIA_PATH)/doc/SkDocument.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkImage.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkImagePriv.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkImage_Codec.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkImage_Raster.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkSurface.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkSurface_Raster.cpp \
				$(EXTERNAL_SKIA_PATH)/pipe/SkGPipeRead.cpp \
				$(EXTERNAL_SKIA_PATH)/pipe/SkGPipeWrite.cpp \
				$(EXTERNAL_SKIA_PATH)/lazy/SkCachingPixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkAddIntersections.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDCubicIntersection.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDCubicLineIntersection.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDCubicToQuads.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDLineIntersection.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDQuadImplicit.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDQuadIntersection.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkDQuadLineIntersection.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkIntersections.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkOpAngle.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkOpContour.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkOpEdgeBuilder.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkOpSegment.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsBounds.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsCommon.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsCubic.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsDebug.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsLine.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsOp.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsPoint.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsQuad.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsRect.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsSimplify.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsTriangle.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathOpsTypes.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkPathWriter.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkQuarticRoot.cpp \
				$(EXTERNAL_SKIA_PATH)/pathops/SkReduceOrder.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/Sk1DPathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/Sk2DPathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkAlphaThresholdFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkArithmeticMode.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkAvoidXfermode.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBicubicImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBitmapSource.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBlurDrawLooper.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBlurMask.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBlurImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkBlurMaskFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkColorFilters.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkColorFilterImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkColorMatrix.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkColorMatrixFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkComposeImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkCornerPathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkDashPathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkDiscretePathEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkDisplacementMapEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkDropShadowImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkEmbossMask.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkEmbossMaskFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkGpuBlurUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkLayerDrawLooper.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkLayerRasterizer.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkLerpXfermode.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkLightingImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkLumaColorFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkMagnifierImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkMatrixConvolutionImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkMergeImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkMorphologyImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkOffsetImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkPaintFlagsDrawFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkPerlinNoiseShader.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkPictureImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkPixelXorXfermode.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkPorterDuff.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkRectShaderImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkStippleMaskFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkTableColorFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkTableMaskFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkTestImageFilters.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkTileImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkMatrixImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkTransparentShader.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/SkXfermodeImageFilter.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkBitmapCache.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkClampRange.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkGradientShader.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkLinearGradient.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkRadialGradient.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkTwoPointRadialGradient.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkTwoPointConicalGradient.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkTwoPointConicalGradient_gpu.cpp \
				$(EXTERNAL_SKIA_PATH)/effects/gradients/SkSweepGradient.cpp \
				$(EXTERNAL_SKIA_PATH)/images/bmpdecoderhelper.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkDecodingImageGenerator.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkForceLinking.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_FactoryDefault.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_FactoryRegistrar.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_wbmp.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libbmp.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libgif.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libico.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libwebp.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libjpeg.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageDecoder_libpng.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageEncoder.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageEncoder_Factory.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkImageEncoder_argb.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkJpegUtility.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkMovie.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkMovie_gif.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkPageFlipper.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkScaledBitmapSampler.cpp \
				$(EXTERNAL_SKIA_PATH)/images/SkStreamHelpers.cpp \
				$(EXTERNAL_SKIA_PATH)/doc/SkDocument_PDF.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFCatalog.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFDevice.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFDeviceFlattener.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFDocument.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFFont.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFFormXObject.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFGraphicState.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFImage.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFPage.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFResourceDict.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFShader.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFStream.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFTypes.cpp \
				$(EXTERNAL_SKIA_PATH)/pdf/SkPDFUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/fonts/SkFontMgr_indirect.cpp \
				$(EXTERNAL_SKIA_PATH)/fonts/SkRemotableFontMgr.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkGlobalInitialization_default.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkMemory_malloc.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkOSFile_posix.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkOSFile_stdio.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkDiscardableMemory_none.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkTime_Unix.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkTLS_pthread.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkXMLParser_empty.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkFontHost_FreeType.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkFontHost_FreeType_common.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkDebug_android.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkFontConfigInterface_android.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkFontConfigParser_android.cpp \
				$(EXTERNAL_SKIA_PATH)/ports/SkFontHost_fontconfig.cpp \
				$(EXTERNAL_SKIA_PATH)/sfnt/SkOTTable_name.cpp \
				$(EXTERNAL_SKIA_PATH)/sfnt/SkOTUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCondVar.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCountdown.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkBase64.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkBitmapHasher.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkBitSet.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkBoundaryPatch.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkFrontBufferedStream.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCamera.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCanvasStack.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCanvasStateUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCubicInterval.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkCullPoints.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkDashPath.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkDeferredCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkDumpCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkEventTracer.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkGatherPixelRefsAndRects.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkInterpolator.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkLayer.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkMatrix22.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkMatrix44.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkMD5.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkMeshUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkNinePatch.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkNWayCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkNullCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkOSFile.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkParse.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkParseColor.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkParsePath.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkPictureUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkPathUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkProxyCanvas.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkSHA1.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkRTConf.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkTextureCompressor.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkThreadUtils_pthread.cpp \
				$(EXTERNAL_SKIA_PATH)/utils/SkThreadUtils_pthread_other.cpp \
				$(EXTERNAL_SKIA_PATH)/fonts/SkGScalerContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAAHairLinePathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAAConvexPathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAARectRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAddPathRenderers_default.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAllocPool.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrAtlas.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrBitmapTextContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrBlend.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrBufferAllocPool.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrCacheable.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrCacheID.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrClipData.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrDefaultPathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrDistanceFieldTextContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrDrawState.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrDrawTarget.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrClipMaskCache.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrClipMaskManager.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrGpu.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrGpuObject.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrGpuFactory.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrInOrderDrawBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrLayerCache.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrMemoryPool.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrOvalRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPaint.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPath.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPathRendererChain.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPathUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrPictureUtils.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrRectanizer_pow2.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrRectanizer_skyline.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrRenderTarget.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrReducedClip.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrResourceCache.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrStencil.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrStencilAndCoverPathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrStencilBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrTraceMarker.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrSWMaskHelper.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrSoftwarePathRenderer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrSurface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrTextContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrTextStrike.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrTexture.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/GrTextureAccess.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrConfigConversionEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrBezierEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrConvolutionEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrConvexPolyEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrBicubicEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrCustomCoordsTextureEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrDashingEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrDistanceFieldTextureEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrDitherEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrOvalEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrRRectEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrSimpleTextureEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrSingleTextureEffect.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrTextureDomain.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/effects/GrTextureStripAtlas.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLAssembleInterface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLBufferImpl.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLCaps.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLExtensions.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLIndexBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLInterface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLNameAllocator.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLNoOpInterface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLPath.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLProgram.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLProgramDesc.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLProgramEffects.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLRenderTarget.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLShaderBuilder.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLSL.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLStencilBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLTexture.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLUtil.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLUniformManager.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLVertexArray.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLVertexBuffer.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGpuGL.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGpuGL_program.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/SkGpuDevice.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/SkGr.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/SkGrFontScaler.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/SkGrPixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/SkGrTexturePixelRef.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkImage_Gpu.cpp \
				$(EXTERNAL_SKIA_PATH)/image/SkSurface_Gpu.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/SkGLContextHelper.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLDefaultInterface_native.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/android/GrGLCreateNativeInterface_android.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/android/SkNativeGLContext_android.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrGLCreateDebugInterface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrBufferObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrTextureObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrTextureUnitObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrFrameBufferObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrShaderObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrProgramObj.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/GrDebugGL.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/debug/SkDebugGLContext.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/GrGLCreateNullInterface.cpp \
				$(EXTERNAL_SKIA_PATH)/gpu/gl/SkNullGLContext.cpp \
	third_party/etc1/etc1.cpp \
	third_party/ktx/ktx.cpp \
				$(EXTERNAL_SKIA_PATH)/core/SkFlate.cpp
				

include $(BUILD_SHARED_LIBRARY)
